name: Sharpass [Windows]

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    defaults:
      run:
        working-directory: ./src

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish -c Release -r win-x64
    - uses: actions/upload-artifact@v4
      with:
        name: Sharpass
        path: D:/a/sharpass/sharpass/src/Sharpass/bin/Release/net8.0/win-x64/publish/Sharpass.exe